import { Station } from "./types";

export const presetStations: Station[] = [
  {
    id: "somafm-groovesalad",
    name: "SomaFM Groove Salad",
    streamUrl: "https://ice2.somafm.com/groovesalad-128-mp3",
    genre: "Ambient/Chill",
    logoUrl: "https://somafm.com/img3/groovesalad-400.jpg",
    isCustom: false,
  },
  {
    id: "somafm-dronezone",
    name: "SomaFM Drone Zone",
    streamUrl: "https://ice2.somafm.com/dronezone-128-mp3",
    genre: "Ambient/Drone",
    logoUrl: "https://somafm.com/img3/dronezone-400.jpg",
    isCustom: false,
  },
  {
    id: "somafm-defcon",
    name: "SomaFM DEF CON Radio",
    streamUrl: "https://ice2.somafm.com/defcon-128-mp3",
    genre: "Electronic/Hacker",
    logoUrl: "https://somafm.com/img3/defcon-400.jpg",
    isCustom: false,
  },
  {
    id: "somafm-spacestation",
    name: "SomaFM Space Station",
    streamUrl: "https://ice2.somafm.com/spacestation-128-mp3",
    genre: "Ambient Space",
    logoUrl: "https://somafm.com/img3/spacestation-400.jpg",
    isCustom: false,
  },
  {
    id: "somafm-secretagent",
    name: "SomaFM Secret Agent",
    streamUrl: "https://ice2.somafm.com/secretagent-128-mp3",
    genre: "Lounge/Spy",
    logoUrl: "https://somafm.com/img3/secretagent-400.jpg",
    isCustom: false,
  },
  {
    id: "jazz24",
    name: "Jazz24",
    streamUrl: "https://live.wostreaming.net/direct/ppm-jazz24aac-ibc1",
    genre: "Jazz",
    isCustom: false,
  },
  {
    id: "kexp",
    name: "KEXP 90.3 FM",
    streamUrl: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3",
    genre: "Indie/Alternative",
    isCustom: false,
  },
  {
    id: "somafm-indie",
    name: "SomaFM Indie Pop Rocks",
    streamUrl: "https://ice2.somafm.com/indiepop-128-mp3",
    genre: "Indie Pop",
    logoUrl: "https://somafm.com/img3/indiepop-400.jpg",
    isCustom: false,
  },
  {
    id: "somafm-beatblender",
    name: "SomaFM Beat Blender",
    streamUrl: "https://ice2.somafm.com/beatblender-128-mp3",
    genre: "Electronic/Deep House",
    logoUrl: "https://somafm.com/img3/beatblender-400.jpg",
    isCustom: false,
  },
  {
    id: "somafm-lush",
    name: "SomaFM Lush",
    streamUrl: "https://ice2.somafm.com/lush-128-mp3",
    genre: "Electronica/Female Vocal",
    logoUrl: "https://somafm.com/img3/lush-400.jpg",
    isCustom: false,
  },
  {
    id: "classical-kusc",
    name: "KUSC Classical",
    streamUrl: "https://kusc.streamguys1.com/kusc-128k.mp3",
    genre: "Classical",
    isCustom: false,
  },
  {
    id: "somafm-thetrip",
    name: "SomaFM The Trip",
    streamUrl: "https://ice2.somafm.com/thetrip-128-mp3",
    genre: "Progressive Electronic",
    logoUrl: "https://somafm.com/img3/thetrip-400.jpg",
    isCustom: false,
  },
  // Korean Radio Stations (verified working)
  {
    id: "ebs-fm",
    name: "EBS FM",
    streamUrl: "https://ebsonair.ebs.co.kr/fmradiofamilypc/familypc1m/playlist.m3u8",
    genre: "Korean Education",
    isCustom: false,
  },
  {
    id: "gugak-fm",
    name: "국악방송 (Gugak FM)",
    streamUrl: "https://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8",
    genre: "Korean Traditional",
    isCustom: false,
  },
  {
    id: "cbs-fm",
    name: "CBS 음악FM 93.9",
    streamUrl: "https://m-aac.cbs.co.kr/cbs939/_definst_/cbs939.stream/playlist.m3u8",
    genre: "Korean Pop/Music",
    isCustom: false,
  },
  {
    id: "ytn-radio",
    name: "YTN 뉴스FM",
    streamUrl: "https://radiolive.ytn.co.kr/radio/_definst_/20211118_fmlive/playlist.m3u8",
    genre: "Korean News",
    isCustom: false,
  },
];
